### ISSUE TITLE
Hygenx Commands Don't work

### ISSUE THREAD

**Issue by idk-pixel** [Arrow-Bot-Discord/Arrow-Bot-Help#1]
Discord commands don't work hx!help no work

**Comment by discord-bot-purchases** [comment]
New prefix is a! Make a new issue for more help

**Comment by discord-bot-purchases** [comment]
Also it's Arrow now to get more info please ask our support server [here](server.arrowbot.xyz)

**Comment by discord-bot-purchases** [comment]
Also for updates like this join our support [here.](https://server.hygenx.ga)
